Mallamed/Areas/Admin/Controllers/SocialWebSiteController.cs
using Core.Helpers;
using Core.Viewmodels.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mallamed.Areas.Admin.Controllers
{
    public class SocialWebSiteController : Controller
    {
        // GET: Admin/SocialWebSite
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult SocialWebSiteList()
        {
            var model = "SP_GetAllSocila".ExecuParamsSqlOrStored(false).AsList<SocialWebSiteVM>();
            return View(model);

        }
        [HttpGet]
        public ActionResult Create()
        {
            SocialWebSiteVM obj = new SocialWebSiteVM();
            return PartialView("~/Areas/Admin/Views/SocialWebSite/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = "SP_SelecSocialWebsiteByIds".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<SocialWebSiteVM>();
            return PartialView("~/Areas/Admin/Views/SocialWebSite/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public ActionResult Create(SocialWebSiteVM model)
        {

            var data = "SP_AddSocialwebsite".ExecuParamsSqlOrStored(false, "Link".KVP(model.Link),"type".KVP(model.type), "Isactive".KVP(model.Isactive), "Id".KVP(model.ID)).AsNonQuery();
            if (data != 0)
            {
                return RedirectToAction("SocialWebSiteList");


            }

            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            try
            {
                var data = "SP_DeleteSocialwebsite".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
                if (data != 0)
                {
                    TempData["msg"] = "<script>alert('تم الحذف ');</script>";

                    return RedirectToAction("SocialWebSiteList");


                }
                else
                {
                    TempData["msg"] = "<script>alert('لم يتم الحذف ');</script>";

                    return RedirectToAction("SocialWebSiteList");
                }
            }
            catch
            {
                TempData["msg"] = "<script>alert(' هذا العنصر مرتبط بجول اخر ولا يمكن الحذف ');</script>";
                return RedirectToAction("GeneralConditionList");
            }
        }
    }
}

Mallamed/Areas/Admin/Views/SocialWebSite/Create.cshtml
@model Core.Viewmodels.Admin.SocialWebSiteVM
@using (Html.BeginForm("Create", "SocialWebSite", new { area = "Admin" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">اضاف حساب جديده</h4>
            </div>

            <input type="text" id="ID" name="ID" value="@Model.ID"hidden />
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="Name" class="control-label">نوع الاكونت  </label>
                            <select class="form-control" id="type" name="type" required >
                                <option value="">يرجي تحديد الموقع</option>
                                <option value="FaceBook">FaceBook</option>
                                <option value="Twitter">Twitter</option>
                                <option value="Instegram">Instegram</option>
                                <option value="Linkedin">Linkedin</option>
                            </select>
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="Name" class="control-label">رابط الاكونت  </label>
                            <input class="form-control" type="text" required name="Link" id="Link" placeholder="رابط الاكونت  "  value="@Model.Link"/>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="Name" class="control-label">العرض  </label>
                            <select class="form-control" id="Isactive" name="Isactive" required>
                                <option value="true">يعرض</option>
                                <option value="false">لا يعرض</option>
                            </select>
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">غلق</button>
                <button type="submit" class="btn btn-info waves-effect waves-light">حفظ الاكونت</button>
            </div>

        </div>
    </div>



}

Mallamed/Areas/Admin/Views/SocialWebSite/SocialWebSiteList.cshtml
@model  IEnumerable<Core.Viewmodels.Admin.SocialWebSiteVM>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@Html.Raw(TempData["msg"])

<div class="content-page">

    <div class="content">
        <div class="container-fluid">



            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        @*<h4 class="page-title">الشروط</h4>*@
                        <ol class="breadcrumb float-left">
                            <li class="breadcrumb-item"><a href="#">الرئسيه</a></li>
                            <li class="breadcrumb-item"><a href="#">  حسابات التواصل</a></li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>




            <div class="row">
                <div class="col-12">
                    <div class="card-box table-responsive">
                        @*<input type="button" id="AddNew" onclick="Create()" class="btn btn-circle blue New" value="Add" />*@
                        @*data-toggle="modal" data-target="#con-close-modal"*@

                        <button type="button" class="btn btn-success waves-effect waves-light" onclick="Create()">اضافه جديد</button>

                        <br />
                        <br />

                        <table id="datatable" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>الكود</th>
                                    <th>نوع الموقع</th>

                                    <th>الرابط</th>
                                    <th>العرض</th>


                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>


                            <tbody>
                                @foreach (var item in Model)
                                {
                                    string st = item.Isactive ? "true" : "false";
                                    string std = item.Isactive ? "يعرض" : "لا يعرض";

                                    <tr>
                                        <td>@item.ID</td>
                                        <td>@item.type</td>
                                        <td>@item.Link</td>
                                        <td>@std</td>

                                        <td>
                                            <button type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light m-b-5" onclick="Edit(@item.ID)" data-target="#con-close-modal">تعديل </button>

                                            @*<button type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light m-b-5">تعديل</button>*@
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Delete",new { Id=item.ID})" class="btn btn-danger btn-rounded w-md waves-effect waves-light m-b-5">حذف</a>

                                        </td>

                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
</div>
<script src="~/Areas/Admin/Scripts/Socialwebsite.js"></script>