Mallamed/Areas/Admin/Controllers/VideoWebSiteController.cs
using Core.Helpers;
using Core.Viewmodels.Admin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mallamed.Areas.Admin.Controllers
{
    public class VideoWebSiteController : Controller
    {
        // GET: Admin/VideoWebSite
        public ActionResult Index()
        {
            var model = "SP_GetAllVideowebsite".ExecuParamsSqlOrStored(false).AsList<VideoWebSiteVM>();
            return View(model);
        }


        [HttpGet]
        public ActionResult Create()
        {
            VideoWebSiteVM obj = new VideoWebSiteVM();
            return PartialView("~/Areas/Admin/Views/VideoWebSite/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = "SP_SelectvideoByIds".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<VideoWebSiteVM>();
            return PartialView("~/Areas/Admin/Views/VideoWebSite/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public ActionResult Create(VideoWebSiteVM model)
        {

            var data = "SP_AddVideoWebsite".ExecuParamsSqlOrStored(false, "Title".KVP(model.Title), "VideoPath".KVP(model.VideoPath), "Isactive".KVP(model.Isactive), "Id".KVP(model.ID)).AsNonQuery();
            if (data != 0)
            {
                return RedirectToAction("Index");


            }


            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            try
            {
                var data = "SP_DeleteVideo".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
                if (data != 0)
                {
                    TempData["msg"] = "<script>alert('تم الحذف ');</script>";

                    return RedirectToAction("Index");


                }
                else
                {
                    TempData["msg"] = "<script>alert('لم يتم الحذف ');</script>";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                TempData["msg"] = "<script>alert(' هذا العنصر مرتبط بجول اخر ولا يمكن الحذف ');</script>";
                return RedirectToAction("GeneralConditionList");
            }
        }
    }
}

Mallamed/Areas/Admin/Views/VideoWebSite/Create.cshtml
@model Core.Viewmodels.Admin.VideoWebSiteVM
@using (Html.BeginForm("Create", "VideoWebSite", new { area = "Admin" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">اضافه فديو  جديد </h4>
            </div>

            <input type="hidden" id="ID" name="ID" value="@Model.ID" />
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="Name" class="control-label">اسم الفديو  </label>
                            <input type="text" class="form-control" required value="@Model.Title" name="Title" id="Title" placeholder="اسم الفديو ">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="Name" class="control-label">إظهار الفديو </label>
                            <select class="form-control" id="Isactive" name="Isactive" required >
                                <option value="true">نعم</option>
                                <option value="false">لا</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="Name" class="control-label">رابط الفديو كامل </label>
                            <input type="text" class="form-control" required value="@Model.VideoPath" name="VideoPath" id="VideoPath" placeholder="http://....... ">
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">غلق</button>
                <button type="submit" class="btn btn-info waves-effect waves-light">حفظ الفديو</button>
            </div>

        </div>
    </div>



}

Mallamed/Areas/Admin/Views/VideoWebSite/Index.cshtml
@model  IEnumerable<Core.Viewmodels.Admin.VideoWebSiteVM>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@Html.Raw(TempData["msg"])


<div class="content-page">

    @*<div class="content">
        <div class="container-fluid">*@



    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                @*<h4 class="page-title">الشروط</h4>*@
                <ol class="breadcrumb float-left">
                    <li class="breadcrumb-item"><a href="#">الرئسيه</a></li>
                    <li class="breadcrumb-item"><a href="#"> فديو </a></li>
                    <li class="breadcrumb-item active">جميع الفديوهات</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />

    <button type="button" class="btn btn-success waves-effect waves-light" onclick="Create()">اضافه جديد</button>


    <div class="row">

        @foreach (var item in Model)
        {
            string visable = item.Isactive ? "true" : "false";
            <div style="width:300px;" id="@item.ID">
                <div class="gal-detail thumb " style="width:340px;">
                    <a href="#" title="@item.Title">
                        <iframe class="thumb-img" style="width: 100%; height: 100%;" src="@item.VideoPath" frameborder="0" allowfullscreen></iframe>
                    </a>
                    <h4 class="text-center">@item.Title</h4>
                    <div class="ga-border"></div>
                    <p class="text-muted text-center">
                        <button type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light m-b-5" onclick="Edit(@item.ID)" data-target="#con-close-modal">تعديل </button>
                        <a href="@Url.Action("Delete",new { Id=item.ID})" class="btn btn-danger btn-rounded w-md waves-effect waves-light m-b-5">حذف</a>

                    </p>
                </div>
            </div>
            <div style="width:80px;"></div>

        }



    </div>



    @*</div>
        </div>*@
</div>






<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">


</div>


@*<script src="~/Areas/Admin/Scripts/Category.js"></script>*@
<script src="~/Areas/Admin/Scripts/VideoWebsite.js"></script>
@*<script src="~/Areas/Admin/Scripts/ImageWebsite.js"></script>*@