Mallamed/Areas/Admin/Controllers/LandMarkTypeController.cs
using Core.Helpers;
using Core.Viewmodels.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mallamed.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    public class LandMarkTypeController : Controller
    {
        // GET: Admin/LandMarkType
        public ActionResult Index()
        {
            var model = "SP_GetAllLandMArkType".ExecuParamsSqlOrStored(false).AsList<LandMArkTypeVm>();
            return View(model);
        }


        [HttpGet]
        public ActionResult Create()
        {
            LandMArkTypeVm obj = new LandMArkTypeVm();
            return PartialView("~/Areas/Admin/Views/LandMarkType/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = "SP_SelectLandTypeById".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<LandMArkTypeVm>();
            return PartialView("~/Areas/Admin/Views/LandMarkType/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public ActionResult Create(LandMArkTypeVm model)
        {

           

            var data = "SP_AdLandType".ExecuParamsSqlOrStored(false, "name".KVP(model.Name),  "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {
                return RedirectToAction("Index");


            }


            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            try
            {
                var data = "SP_DeleteLandType".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
                if (data != 0)
                {
                    TempData["msg"] = "<script>alert('تم الحذف ');</script>";

                    return RedirectToAction("Index");


                }
                else
                {
                    TempData["msg"] = "<script>alert('لم يتم الحذف ');</script>";

                    return RedirectToAction("Index");
                }

            }
            catch
            {
                TempData["msg"] = "<script>alert(' هذا العنصر مرتبط بجول اخر ولا يمكن الحذف ');</script>";

                return RedirectToAction("Index");
            }

        }
    }
}

Mallamed/Areas/Admin/Views/LandMarkType/Create.cshtml
@model Core.Viewmodels.Admin.LandMArkTypeVm
@using (Html.BeginForm("Create", "LandMarkType", new { area = "Admin" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">اضافه انواع المعالم </h4>
            </div>

            <div class="modal-body">

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <input type="text" class="form-control" hidden id="Id" value="@Model.Id" name="Id">

                            <label for="field-3" class="control-label">الاسم </label>
                            <input type="text" class="form-control" required id="Name" value="@Model.Name" name="Name" placeholder="الاسم ">
                        </div>
                    </div>
                </div>

            </div>

            <div class="modal-footer">
                <input type="submit" class="btn btn-info waves-effect waves-light"  value="حفظ" />
                <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">اغلاق</button>

            </div>
            
        </div>
    </div>



}

Mallamed/Areas/Admin/Views/LandMarkType/Index.cshtml
@model  IEnumerable<Core.Viewmodels.Admin.LandMArkTypeVm>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@Html.Raw(TempData["msg"])


<div class="content-page">

    <div class="content">
        <div class="container-fluid">



            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        @*<h4 class="page-title">الشروط</h4>*@
                        <ol class="breadcrumb float-left">
                            <li class="breadcrumb-item"><a href="#">الرئسيه</a></li>
                            <li class="breadcrumb-item"><a href="#"> انواع المعالم</a></li>
                            <li class="breadcrumb-item active">جميع انواع المعالم</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>




            <div class="row">
                <div class="col-12">
                    <div class="card-box table-responsive">
                        @*<input type="button" id="AddNew" onclick="Create()" class="btn btn-circle blue New" value="Add" />*@
                        @*data-toggle="modal" data-target="#con-close-modal"*@

                        <button type="button" class="btn btn-success waves-effect waves-light" onclick="Create()">اضافه جديد</button>

                        <br />
                        <br />

                        <table id="datatable" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>رقم التسلسل</th>
                                    <th>الاسم  </th>


                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>


                            <tbody>
                                @foreach (var item in Model)
                                {

                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>


                                        <td>
                                            <button type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light m-b-5" onclick="Edit(@item.Id)" data-target="#con-close-modal">تعديل </button>

                                            @*<button type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light m-b-5">تعديل</button>*@
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Delete",new { Id=item.Id})" class="btn btn-danger btn-rounded w-md waves-effect waves-light m-b-5">حذف</a>

                                        </td>

                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
</div>
<script src="~/Areas/Admin/Scripts/LandMarkType.js"></script>