Mallamed/Areas/Admin/Controllers/CategoryController.cs
using Core.Helpers;
using Core.Viewmodels.Admin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mallamed.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    public class CategoryController : Controller
    {
        // GET: Admin/Category
        public ActionResult Index()
        {
            var model = "SP_GetAllCategorys".ExecuParamsSqlOrStored(false).AsList <CategorysVm>();
            return View(model);
        }


        [HttpGet]
        public ActionResult Create()
        {
            CategorysVm obj = new CategorysVm();
            return PartialView("~/Areas/Admin/Views/Category/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = "SP_SelectCatById".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<CategorysVm>();
            return PartialView("~/Areas/Admin/Views/Category/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public ActionResult Create(CategorysVm model)
        {

            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileNameWithExtension = Path.GetFileName(file.FileName);
                    var fileNameOnly = Path.GetFileNameWithoutExtension(file.FileName);
                    string RootPath = Server.MapPath("~/Uploads/Images/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique = new Guid();
                    var path = Path.Combine(RootPath, fileNameOnly + unique + Path.GetExtension(file.FileName));
                    file.SaveAs(path);
                    model.Photo ="Images/"+ fileNameOnly + unique + Path.GetExtension(file.FileName);

                }
            }
           
           
            var data = "SP_AdCategory".ExecuParamsSqlOrStored(false, "name".KVP(model.Name), "Photo".KVP(model.Photo), "Id".KVP(model.ID)).AsNonQuery();
            if (data != 0)
            {
                TempData["msg"] = "<script>alert(' تم الاضافه بنجاح');</script>";

                return RedirectToAction("Index");


            }


            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteCategory(int Id)
        {
            try{
                var data = "SP_DeleteCategory".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
                if (data != 0)
                {
                    TempData["msg"] = "<script>alert(' تم الحذف');</script>";

                    return RedirectToAction("Index");


                }
                return Json(new { message = "Erro" });

            }
            catch
            {
                TempData["msg"] = "<script>alert(' هذا العنصر مرتبط بجول اخر ولا يمكن الحذف ');</script>";
                return RedirectToAction("Index");

            }

        }
    }
}

Mallamed/Areas/Admin/Controllers/DonatorsController.cs
using Core.Helpers;
using Core.Viewmodels.Admin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Mallamed.Entity;
using Mallamed.Models;
using System.Net;
using Newtonsoft.Json;

namespace Mallamed.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    public class DonatorsController : Controller
    {
        // GET: Admin/Donators
        MallamDbFEntities db = new MallamDbFEntities();

        private ApplicationUserManager _userManager;

        public DonatorsController()
        {
            //UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ActionResult Index()
        {
            var model = "SP_GetAlldonators".ExecuParamsSqlOrStored(false).AsList<DonatorsVM>();
            return View(model);
        }
        public ActionResult Create(int Catid=0,int RegionId=0)
        {

            var lst3 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst3.AddRange("Sp_CityDrop".ExecuParamsSqlOrStored(false).AsList<CityDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.Cities = lst3;
            var RegionList = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            RegionList.AddRange("Sp_RegionDrop".ExecuParamsSqlOrStored(false).AsList<RegionDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.ID.ToString(),
                Selected = s.ID == RegionId ? true : false
            }).ToList());
            ViewBag.RegionId = RegionList;

            var lst = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst.AddRange("Sp_CatDrop".ExecuParamsSqlOrStored(false).AsList<CatDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.ID.ToString(),
                Selected = s.ID == Catid ? true : false
            }).ToList());
            ViewBag.Categories = lst;
            var lst1 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst1.AddRange("Sp_RegionDrop".ExecuParamsSqlOrStored(false).AsList<RegionDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.ID.ToString(),
                Selected = s.ID == RegionId ? true : false
            }).ToList());
            ViewBag.ListRegion = lst1;
            DonatorsFM obj = new DonatorsFM();

            return View("~/Areas/Admin/Views/Donators/Create.cshtml", obj);
        }
        [HttpPost]
        public ActionResult Create(DonatorsFM model)
        {
            try
            {
                var data = "SP_AddDontars".ExecuParamsSqlOrStored(false, "OwnName".KVP(model.OwnName), "OrgName".KVP(model.OrgName), "Versiondate".KVP(model.Versiondate), "ContractDate".KVP(model.ContractDate), "finishDate".KVP(model.finishDate), "VisiteDate".KVP(model.VisiteDate), "DiscountDate".KVP(model.DiscountDate),
                   "ResponsableName".KVP(model.ResponsableName), "RegionId".KVP(model.RegionId), "BookName".KVP(model.BookName), "Email".KVP(model.Email), "Phone1".KVP(model.Phone1), "Phone2".KVP(model.Phone2),
                   "Telephone".KVP(model.Telephone), "TradeActivity".KVP(model.TradeActivity), "Address".KVP(model.Address), "CatID".KVP(model.CatID), "Id".KVP(model.ID)).AsNonQuery();
                if (data != 0)
                {
                    var result = "-1";
                    var webAddr = "https://fcm.googleapis.com/fcm/send";
                    var httpWebRequest = (HttpWebRequest)WebRequest.Create(webAddr);

                    httpWebRequest.ContentType = "application/json";
                    var firebasekey = System.Configuration.ConfigurationManager.AppSettings["FireBaseKey"];
                    httpWebRequest.Headers.Add(HttpRequestHeader.Authorization, "key=" + firebasekey);
                    httpWebRequest.Method = "POST";
                    using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
                    {
                        FireBaseData data1 = new FireBaseData();
                        data1.ShortDesc = "Notfication";
                        data1.Description = "تم اضافة معلم تجارى جديد";
                        FireBaseNotfication notfication = new FireBaseNotfication();
                        notfication.title = "Notfication";
                        notfication.text = "تم اضافة معلم جديد";

                        FireBaseObject obj = new FireBaseObject();
                        var Tokens = "SP_GetAllToken".ExecuParamsSqlOrStored(false).AsList<TokensVM>();
                        foreach (var item in Tokens)
                        {
                            obj.to = item.Token;
                            obj.data = data1;
                            obj.notification = notfication;

                            obj.sound = "default";
                            string strNJson = JsonConvert.SerializeObject(obj);

                            streamWriter.Write(strNJson);
                            streamWriter.Flush();
                        }
                        
                    }

                    var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
                    using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
                    {
                        result = streamReader.ReadToEnd();
                        Console.WriteLine(streamReader.ReadToEnd());
                    }
                    return RedirectToAction("Index");


                }

            }
            catch (Exception ex)
            {
                TempData["error"] = "يرجي ملئ  التاريخ بشكل صحيح ";
            }

            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit1(int Id,int Catid = 0,int RegionId=0)
        {
            var lst = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst.AddRange("Sp_CatDrop".ExecuParamsSqlOrStored(false).AsList<CatDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.ID.ToString(),
                Selected = s.ID == Catid ? true : false
            }).ToList());
            ViewBag.Categories = lst;
            var lst1 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst1.AddRange("Sp_RegionDrop".ExecuParamsSqlOrStored(false).AsList<RegionDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.ID.ToString(),
                Selected = s.ID == RegionId ? true : false
            }).ToList());
            ViewBag.ListRegion = lst1;
            var lst3 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst3.AddRange("Sp_CityDrop".ExecuParamsSqlOrStored(false).AsList<CityDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.Cities = lst3;

            var model = "SP_SelectDonatrosById".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<DonatorsFM>();
            return View("~/Areas/Admin/Views/Donators/Create.cshtml", model.FirstOrDefault());
        }


        [HttpPost]
        public ActionResult SetSocialMedia(DonatorContact contact)
        {

            try
            {
                db.DonatorContacts.AddOrUpdate(contact);
                db.SaveChanges();
                TempData["error"] = "تم الاضافة بنجاح";
            }
            catch (Exception)
            {
                TempData["error"] = "يرجي ادخال البيانات صحيحة";
            }
            return RedirectToAction("Details", new { id = contact.DonatorID });
        }
        public void DeleteSocial(int id)
        {
            var con = db.DonatorContacts.Find(id);
            int? ids = con.DonatorID;
            db.DonatorContacts.Remove(con);
            db.SaveChanges();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            var don = db.Donators.Include(c => c.DonatServices.Select(e => e.TempDiscountServices)).FirstOrDefault(c => c.ID == id);
            if (don == null)
                return RedirectToAction("Index");
            var err = TempData["error"] != null ? TempData["error"].ToString() : "";
            ModelState.AddModelError("", err);
            ViewBag.CatID = new SelectList(db.Categorys, "ID", "Name", don.CatID);
            ViewBag.RegionId = new SelectList(db.Regions, "ID", "Name", don.RegionId);
            ViewBag.cons = db.GeneralConditions.ToList();

            return View(don);
        }
        [HttpGet]
        public ActionResult Edits(int? id)
        {
            var donator = new Donator();
            if (id != null)
            {
                ViewBag.tit = "تعديل معلومات المانح";
                donator = db.Donators.Find(id);
                ViewBag.CatID = new SelectList(db.Categorys, "ID", "Name", donator.CatID);

Mallamed/Controllers/DonatorController.cs
using Mallamed.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Mallamed.Controllers
{
    public class DonatorController : Controller
    {
        private readonly MallamDbFEntities db = new MallamDbFEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? Id)
        {
            return View(db.Donators.Where(x => x.ID == Id).FirstOrDefault());
        }

        #region Partial Views

        public PartialViewResult Categories()
        {
            var model = db.Categorys.Include("Donators").ToList();
            return PartialView("_Categories",model );
        }

        public PartialViewResult Regions()
        {
            return PartialView("_Regions", db.Regions.Include("Donators").ToList());
        }

        #endregion

        #region Ajax

        public PartialViewResult GetDonators(int? Id, string type)
        {
            if (Id != null)
            {
                List<Donator> Donators = new List<Donator>();

                if (type == "cat")
                {
                    var cat = db.Categorys.Where(x => x.ID == Id).FirstOrDefault();
                    ViewBag.Name = cat.Name;
                    Donators = cat.Donators.Where(x=>x.IsActive == 1 || x.IsActive == 2).ToList();
                }
                else
                {
                    var reg = db.Regions.Where(x => x.ID == Id).FirstOrDefault();
                    if (reg != null)
                    {
                        ViewBag.Name = reg.Name;
                        Donators = reg.Donators.Where(x => x.IsActive == 1 || x.IsActive == 2).ToList();
                    }
                    else
                    {
                        ViewBag.Name = "";
                    }
                }
                return PartialView("_GetDonators", Donators);
            }
            else
            {
                var cat = db.Categorys.FirstOrDefault();
                ViewBag.Name = cat.Name;
                return PartialView("_GetDonators", cat.Donators.Where(x => x.IsActive == 1 || x.IsActive == 2).ToList());
            }
        }

        #endregion

    }
}

Mallamed/Controllers/ServicesController.cs
using Mallamed.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace Mallamed.Controllers
{
    public class ServicesController : Controller
    {
        MallamDbFEntities db = new MallamDbFEntities();
        public ActionResult Index()
        {
            ViewBag.name = "الاقسام";
            var cates = db.Categorys.ToList();
            return View(cates);
        }


        public ActionResult Categorys()
        {
            var cates = db.Categorys.ToList();
            return PartialView(cates);
        }


        public ActionResult Regions()
        {
            var Regions = db.Regions.ToList();
            return PartialView(Regions);
        }
        public ActionResult Donators(int? id,string type,int?page)
        {
            ViewBag.id = id;
            ViewBag.type = type;
            var donators = new List<Donator>();
            if (id == null)
            {
                return RedirectToAction("Index");
            }
                ViewBag.name = "الخدمات الدائمة والمؤقتة";
            if (type == "r") 
                donators = db.Donators.Where(c => c.RegionId == id).Where(c => c.IsActive == 1 || c.IsActive == 2).ToList();
            else
                donators = db.Donators.Where(c=>c.CatID==id).Where(c => c.IsActive == 1 || c.IsActive == 2).ToList();

            return View(donators.ToPagedList(page??1,12));
        }
        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                var don = db.Donators.Find(id);
                if (don != null)
                {
                    return View(don);
                }
            }

            return RedirectToAction("Index");
        }
    }
    public class GetSevices
    {
        public List<Category> Categorys { get; set; }

        public List<Region> Regions { get; set; }
    }
}

Mallamed/Views/Services/Categorys.cshtml
@model IEnumerable<Mallamed.Entity.Category>
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
@Html.Partial("~/Views/shared/_HeadLine.cshtml", new Dictionary<string, string> { { Url.Action("Categorys"), "القسم التجارى" } })

<div class="sidebar white-bg">
    <h3 class="sidebar-title">الاقسام</h3>
    <!-- Manufacturer Start -->
    <div class="manufacturer mb-30">
        <ul class="pt-5">
            @foreach (var item in Model)
            {
                <li><a href="@Url.Action("Donators",new { id=item.ID,type="d"})">@item.Name <span>(@item.Donators.Count())</span></a></li>
            }
        </ul>
    </div>
    <!-- Manufacturer End -->
</div>

Mallamed/Views/Services/Donators.cshtml
@model PagedList.IPagedList<Mallamed.Entity.Donator>
@using PagedList.Mvc;
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
<style>
    .rating i {
        color: #f7bc3d;
        font-size: 20px;
        letter-spacing: 1px;
    }
</style>
<div class="accessories ptb-50">
    <div class="container">
        <div class="section-title mb-50">
            <h2>
                @ViewBag.name
            </h2>
        </div>
        <div class="row">
            <div class="col-lg-9 col-lg-push-3 col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
                <div class="main-categorie">
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            <div class="col-md-4 col-sm-6">
                                @{double total = 0;
                                    var sum = item.EvaluationClients.Sum(c => c.Evaluate);
                                    var count = item.EvaluationClients.Count;
                                    if (count == 0) { count = 1; }
                                    total = sum / count;
                                    decimal? tempDiscount = 0;
                                    var datetime = item.DiscountDate ?? DateTime.Now;
                                    if (item.TempDiscountServices.Count(c => c.IsAccepted == true || c.IsOrder == false) > 0)
                                    {
                                        var first = item.TempDiscountServices.OrderByDescending(c => c.DateTo).OrderByDescending(c => c.Discount).FirstOrDefault(c => c.IsAccepted == true || c.IsOrder == false);
                                        if (first != null)
                                        {
                                            datetime = first.DateForm ?? DateTime.Now;
                                            tempDiscount = first.Discount;
                                        }
                                    }
                                }
                                <div class="single-product">
                                    <!-- Product Image Start -->
                                    <div class="pro-img">
                                        <a href="@Url.Action("Details","Services",new { id=item.ID})">
                                            <img class="primary-img" src="@item.Photo" alt="offer-pro">
                                            <img class="secondary-img" src="@item.Photo" alt="offer-pro">
                                        </a>
                                    </div>
                                    <!-- Product Image End -->
                                    <!-- Product Content Start -->
                                    <div class="pro-content">
                                        <h4><a href="@Url.Action("Details","Services",new { id=item.ID})">@item.OrgName</a></h4>
                                        @{
                                            var first2 = item.DonatServices.OrderByDescending(c => c.ID).OrderByDescending(c => c.Discount).FirstOrDefault();
                                            if (first2 != null)
                                            {
                                                if (tempDiscount == 0)
                                                {
                                                    <p><span>-@first2.Discount %</span></p>
                                                }
                                                else
                                                {
                                                    <p><span>-@tempDiscount %</span><del>-@first2.Discount %</del></p>
                                                }
                                            }
                                            else
                                            {
                                                <p><span>-@tempDiscount %</span></p>
                                            }
                                        }
                                        <div class="rating">
                                            @if (total > 4)
                                            {
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                            }
                                            else if (total > 3)
                                            {
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                            }
                                            else if (total > 2)
                                            {
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                            }
                                            else if (total > 1)
                                            {
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                            }
                                            else if (total > 0)
                                            {
                                                <i class="zmdi zmdi-star"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                            }
                                            else
                                            {
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                                <i class="zmdi zmdi-star-outline"></i>
                                            }
                                        </div>
                                        @if (tempDiscount == 0)
                                        {
                                            if (first2 != null)
                                            {
                                                <span class="sticker-sale pro-sticker">-@first2.Discount %</span>
                                            }
                                            else
                                            {
                                                <span class="sticker-sale pro-sticker">-0 %</span>

                                            }

                                        }
                                        else
                                        {
                                            <span class="sticker-sale pro-sticker">-@tempDiscount %</span>
                                        }

                                    </div>
                                    <!-- Product Content End -->
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-lg-pull-9 col-md-3 col-md-pull-9 col-sm-4 col-sm-pull-8">
                @Html.Action("Categorys", "Services")
                @Html.Action("Regions", "Services")
            </div>
        </div>

    </div>
</div>
@if (Model.PageCount > 1)
{
    <div class="pageList" id="cen" style="text-align: center;">
        @Html.PagedListPager(Model, page => Url.Action("Donators", new { page, id = ViewBag.id, type = ViewBag.type }))
    </div>
}

Mallamed/Views/Services/Index.cshtml
@model IEnumerable<Mallamed.Entity.Category>
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<div class="accessories ptb-50">
    <div class="container">
        <div class="section-title mb-50">
            <h2>
                الاقسام
            </h2>
        </div>
        <div class="row">
            <div class="col-lg-9 col-lg-push-3 col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
                <div class="main-categorie">
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            <div class="col-md-4 col-sm-6">
                                <div class="single-product">
                                    <div class="pro-img">
                                        <a href="@Url.Action("Donators",new { id=item.ID,type="d"})">
                                            <img class="primary-img" src="@item.Photo" alt="offer-pro">
                                            <img class="secondary-img" src="@item.Photo" alt="offer-pro">
                                        </a>
                                    </div>
                                    <div class="pro-content">
                                        <h4><a href="@Url.Action("Donators",new { id=item.ID,type="d"})">@item.Name <small>(@item.Donators.Count)</small></a></h4>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-lg-pull-9 col-md-3 col-md-pull-9 col-sm-4 col-sm-pull-8">
                @Html.Action("Categorys", "Services")
                @Html.Action("Regions", "Services")
            </div>
        </div>

    </div>
</div>

Mallamed/Views/Services/Regions.cshtml
@model IEnumerable<Mallamed.Entity.Region>

@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
<div class="sidebar white-bg">
    <h3 class="sidebar-title">المناطق</h3>
    <!-- Manufacturer Start -->
    <div class="manufacturer mb-30">
        <ul class="pt-5">
            @foreach (var item in Model)
            {
                <li><a href="@Url.Action("Donators",new { id=item.ID,type="r"})">@item.Name <span>(@item.Donators.Count())</span></a></li>
            }
        </ul>
    </div>
    <!-- Manufacturer End -->
</div>